config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'events/index'
  end
  root to: 'homes#top'

  devise_for :admin, controllers: {
    registrations: 'admin/registrations',
    sessions: 'admin/sessions'
  }
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  scope module: :public do
    resources :corporates, only: %i[index show] do
      get :search, on: :collection
    end
    resources :reports do
      get :search, on: :collection
      resource :favorites, only: %i[create destroy]
      resources :comments, only: %i[create destroy]
    end
    resources :events
  end
  namespace :admin do
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdrawal/:id' => 'customers#withdrawal', as: 'withdrawal'
    resources :corporates, only: %i[new create show edit update index destroy] do
        get :search, on: :collection
    end
    resources :reports, only: %i[show index]
    resources :customers do
      get :search, on: :collection
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/corporate.rb
class Corporate < ApplicationRecord
  has_many :reports, dependent: :destroy

  validates :name, presence: true
  validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :annual_saleses, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :employees, presence: true
  validates :bases, presence: true

end

app/controllers/admin/corporates_controller.rb
class Admin::CorporatesController < ApplicationController
  def new
    @corporate = Corporate.new
  end

  def create
    @corporate = Corporate.new(corporate_params)
    if @corporate.save
      redirect_to  admin_corporate_path(@corporate.id)
    else
      render :new
    end
  end

  def show
    @corporate = Corporate.find(params[:id])
  end

  def index
    @corporates = Corporate.page(params[:page])
  end
  def search
    @corporates = if params[:name].present?

                    Corporate.where('name LIKE :param OR phone_number LIKE :param OR name_kana LIKE :param', param: "%#{params[:name]}%").page(params[:page])
                  else
                    Corporate.none.page(params[:page])
                  end
    render :index
  end

  def edit
    @corporate = Corporate.find(params[:id])
  end

  def update
    corporate = Corporate.find(params[:id])
    corporate.update(corporate_params)
    redirect_to admin_corporate_path(corporate.id)
  end

  def destroy
    corporate = Corporate.find(params[:id])
    corporate.destroy
    redirect_to admin_corporates_path

  end

  private

  def corporate_params
    params.require(:corporate).permit(:name, :name_kana, :annual_saleses, :industories, :employees, :bases, :corporate_info,
                                      :phone_number, :address)
  end
end

app/helpers/admin/corporates_helper.rb
module Admin::CorporatesHelper
end

app/views/admin/corporates/edit.html.erb
<h4>企業編集</h4>
<%= form_with model: @corporate,url: admin_corporate_path do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <%= f.label :企業名 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :name %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <%= f.label :フリガナ %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :name_kana %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
       <%= f.label :年商 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :annual_saleses %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
     <%= f.label :住所 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :address %>
    </div>
    <div class="col-lg-2"></div>
  </div>

   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :電話番号 %>
    </div>
    <div class="col-lg-4">
    <%= f.text_field :phone_number %>
    </div>
    <div class="col-lg-2"></div>
  </div>
   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :従業員数 %>
    </div>
    <div class="col-lg-4">
    <%= f.text_field :employees %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :拠点数 %>
    </div>
    <div class="col-lg-4">
    <%= f.text_field :bases %>
    </div>
    <div class="col-lg-2"></div>
  </div>
   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :ホームページ %>
    </div>
    <div class="col-lg-4">
    <%= f.text_field :corporate_info %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.submit'編集完了' %>
    </div>
    <div class="col-lg-4">
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>
<% end %>

app/views/admin/corporates/index.html.erb
<h4>企業一覧</h4>
<div class="container">
  <%= form_with url: search_corporates_path, method: :get, local: true do |f| %>
  <%= f.text_field :name,:placeholder => "企業名・電話番号で検索" %>
  <%= f.submit :企業検索 %>
  <% end %>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">
      <%= link_to new_admin_corporate_path ,class: 'btn btn-primary' ,method: :get do %>
      <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
  <table class="table table-striped table-bordered">
    <tr>
      <th>企業名</th>
      <th>住所</th>
      <th>電話番号</th>
    </tr>
  <% @corporates.each do |corporate| %>
    <tr>
      <td><%= link_to corporate.name, admin_corporate_path(corporate.id) %></td>
      <td><%= corporate.address %></td>
      <td><%= corporate.phone_number %></td>
    </tr>
     <% end %>

  </table>
  <div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4"><%= paginate(@corporates) %></div>
    <div class="col-lg-4"></div>
  </div>
</div>

app/views/admin/corporates/new.html.erb
<h4>企業登録</h4>
<% if @corporate.errors.any? %>
  <%= @corporate.errors.count %>件のエラーが発生しました
  <ul>
    <% @corporate.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @corporate,url: admin_corporates_path, local:true do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <%= f.label :企業名 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :name %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <%= f.label :フリガナ %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :name_kana %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
       <%= f.label :"年商(百万)" %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :annual_saleses %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
     <%= f.label :住所 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :address %>
    </div>
    <div class="col-lg-2"></div>
  </div>

   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :電話番号 %>
    </div>
    <div class="col-lg-4">
    <%= f.text_field :phone_number,:placeholder => "ハイフンなし" %>
    </div>
    <div class="col-lg-2"></div>
  </div>
   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :従業員数 %>
    </div>
    <div class="col-lg-4">
    <%=f.text_field :employees %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :拠点数 %>
    </div>
    <div class="col-lg-4">
    <%=f.text_field :bases %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :ホームページ %>
    </div>
    <div class="col-lg-4">
    <%= f.text_field :corporate_info %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.submit'新規登録' %>
    </div>
    <div class="col-lg-4">
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>
  <% end %>

app/views/admin/corporates/show.html.erb
<h4><%= @corporate.name %>の詳細</h4>

<div class="container">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">企業名</div>
    <div class="col-lg-3"><%= @corporate.name %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">年商</div>
    <div class="col-lg-3"><%= @corporate.annual_saleses %>(百万)円</div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">住所</div>
    <div class="col-lg-3"><%= @corporate.address %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">電話番号</div>
    <div class="col-lg-3"><%= @corporate.phone_number %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">従業員数</div>
    <div class="col-lg-3"><%= @corporate.employees %>人</div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">拠点数</div>
    <div class="col-lg-3"><%= @corporate.bases %>ヶ所</div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">ホームページ</div>
    <div class="col-lg-3">
      <% if @corporate.corporate_info.nil? %>
        <%= @corporate.corporate_info %>
      <% else %>
        <%= raw Rinku.auto_link(h(@corporate.corporate_info)) %>
      <% end %>
      </div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3"><%= link_to "編集する",edit_admin_corporate_path(@corporate.id),class: 'btn btn-success' %></div>
    <div class="col-lg-3"><%= link_to "削除する",admin_corporate_path(@corporate.id),method: :delete,class: 'btn btn-danger',"data-confirm" => "本当に削除しますか？" %></div>
    <div class="col-lg-3"></div>
  </div>
</div>