config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'events/index'
  end
  root to: 'homes#top'

  devise_for :admin, controllers: {
    registrations: 'admin/registrations',
    sessions: 'admin/sessions'
  }
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  scope module: :public do
    resources :corporates, only: %i[index show] do
      get :search, on: :collection
    end
    resources :reports do
      get :search, on: :collection
      resource :favorites, only: %i[create destroy]
      resources :comments, only: %i[create destroy]
    end
    resources :events
  end
  namespace :admin do
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdrawal/:id' => 'customers#withdrawal', as: 'withdrawal'
    resources :corporates, only: %i[new create show edit update index destroy] do
        get :search, on: :collection
    end
    resources :reports, only: %i[show index]
    resources :customers do
      get :search, on: :collection
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites,dependent: :destroy
  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :name, presence: true
  validates :name_kana,presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :email, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def unsubscribe
    @customer = Customer.find(params[:id])
  end

  def withdrawal
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    # reset_session
    flash[:notice] = '退会処理を実行いたしました'
    redirect_to admin_customers_path
  end

  def index
    @customers = Customer.page(params[:page])
  end

  def search
    @customers = if params[:name].present?

                   Customer.where('name LIKE ?', "%#{params[:name]}%").page(params[:page])
                 else
                   Customer.none.page(params[:page])
                 end
    render :index
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to admin_customers_path(@customer.id)
    else
      render :new
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    puts customer.valid?
    puts customer.invalid?
    redirect_to admin_customer_path(customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :password, :name, :name_kana, :address, :telephone_number,:is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h4><%= @customer.name %>さんの編集画面</h4>
<%= form_with model: @customer,url: admin_customer_path do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <%= f.label :名前 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :name %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <%= f.label :フリガナ %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :name_kana %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
       <%= f.label :住所 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :address %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
     <%= f.label :電話番号 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :telephone_number %>
    </div>
    <div class="col-lg-2"></div>
  </div>

   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :メールアドレス %>
    </div>
    <div class="col-lg-4">
    <%= f.text_field :email %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">会員ステータス</div>
    <div class="col-lg-1"><%= f.radio_button :is_deleted, false %>在籍中</div>
    <div class="col-lg-1"><%= f.radio_button :is_deleted, true  %>退職済</div>
    <div class="col-lg-4"></div>
  </div>
   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :password %>
    </div>
    <div class="col-lg-4">
    <%=f.password_field :password %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.submit'編集完了', class: 'btn btn-primary' %>
    </div>
    <div class="col-lg-4"><%= link_to "退会する", admin_unsubscribe_path(id: @customer.id), class: 'btn btn-danger' %></div>
    <div class="col-lg-2"></div>
  </div>

</div>
<% end %>

app/views/admin/customers/index.html.erb
<h5>社員一覧</h5>
<div class="container">
  <%= form_with url:  search_admin_customers_path, method: :get, local: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit :社員検索 %>
  <% end %>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">
      <%= link_to new_admin_customer_path,class: 'btn btn-primary' ,method: :get do %>
      <i class="fas fa-user-plus"></i>
      <% end %>
    </div>
  </div>

  <table class="table table-striped table-bordered">
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>電話番号</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
      <td><%= customer.telephone_number %></td>
      <td><%= customer.email %></td>
      <td>
          <% if customer.is_deleted %>
          退職済
          <% else %>
          在職中
          <% end %>
      </td>
    <% end %>
    </tr>
  
  </table>

  <div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4"><%= paginate(@customers) %></div>
    <div class="col-lg-4"></div>
  </div>
</div>

app/views/admin/customers/new.html.erb
<h4>社員登録</h4>
<% if @customer.errors.any? %>
  <%= @customer.errors.count %>件のエラーが発生しました
  <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @customer, url: admin_customers_path, local: true do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <%= f.label :名前 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :name %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <%= f.label :フリガナ %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :name_kana %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
       <%= f.label :住所 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :address %>
    </div>
    <div class="col-lg-2"></div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
     <%= f.label :電話番号 %>
    </div>
    <div class="col-lg-4">
      <%= f.text_field :telephone_number %>
    </div>
    <div class="col-lg-2"></div>
  </div>

   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :メールアドレス %>
    </div>
    <div class="col-lg-4">
    <%= f.text_field :email %>
    </div>
    <div class="col-lg-2"></div>
  </div>
   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.label :password %>
    </div>
    <div class="col-lg-4">
    <%=f.password_field :password %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
    <%= f.submit %>
    </div>
    <div class="col-lg-4">
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>
  <% end %>

app/views/admin/customers/show.html.erb
<h4><%= @customer.name %>の詳細</h4>
<div class="container">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">ID</div>
    <div class="col-lg-3"><%= @customer.id %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">名前</div>
    <div class="col-lg-3"><%= @customer.name %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">フリガナ</div>
    <div class="col-lg-3"><%= @customer.name_kana %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">住所</div>
    <div class="col-lg-3"><%= @customer.address %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">電話番号</div>
    <div class="col-lg-3"><%= @customer.telephone_number %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">メールアドレス</div>
    <div class="col-lg-3"><%= @customer.email %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"><%= link_to "編集する",edit_admin_customer_path(@customer.id),class: 'btn btn-success' %></div>
    <div class="col-lg-3"></div>
  </div>
</div>

app/views/admin/customers/unsubscribe.html.erb
<div class="container">
 <div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
   <h2>本当に退会しますか</h2>
  </div>
  <div class="col-lg-3"></div>
 </div>

 <div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
   <p>
     退会すると、会員登録情報や<br>
     これまでの購入履歴が閲覧できなくなります<br>
     退会する場合は、「退会する」をクリックしてください。<br>

   </p>
  </div>
  <div class="col-lg-3"></div>
 </div>
 <div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-3"><%= link_to "退会する", admin_withdrawal_path(id: @customer.id), class: 'btn btn-danger', method: :patch, "data-confirm" => "本当に削除しますか？"  %></div>
  <div class="col-lg-3"><%= link_to "退会しない", edit_admin_customer_path(@customer.id),class: 'btn btn-primary' %></div>
  <div class="col-lg-3"></div>
 </div>
  </div>