config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'events/index'
  end
  root to: 'homes#top'

  devise_for :admin, controllers: {
    registrations: 'admin/registrations',
    sessions: 'admin/sessions'
  }
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  scope module: :public do
    resources :corporates, only: %i[index show] do
      get :search, on: :collection
    end
    resources :reports do
      get :search, on: :collection
      resource :favorites, only: %i[create destroy]
      resources :comments, only: %i[create destroy]
    end
    resources :events
  end
  namespace :admin do
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdrawal/:id' => 'customers#withdrawal', as: 'withdrawal'
    resources :corporates, only: %i[new create show edit update index destroy] do
        get :search, on: :collection
    end
    resources :reports, only: %i[show index]
    resources :customers do
      get :search, on: :collection
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :corporate
  belongs_to :customer
  has_many :favorites,dependent: :destroy

   def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
   end

  validates :report_text, presence: true
  validates :result, presence: true
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @reports = Report.page(params[:page])
  end

  def show
    @report = Report.find(params[:id])
    @customer = @report.customer
    @result = { '1' => 'アポ取得', '2' => 'アポ未取得', '3' => '日程調整中' }
  end

  private

  def report_params
    params.require(:report).permit(:report_text, :result, :next, :corporate_id)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<h5>日報一覧</h5>
<div class="container">

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>日時</th>
        <th>企業名</th>
        <th>登録者</th>
        <th>コメント数</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @reports.each do |report| %>
      <tr>
        <td><%= report.created_at.to_s(:datetime_jp) %></td>
        <td><%= report.corporate.name %></td>
        <td><%= report.customer.name %></td>
        <td><%= link_to "#{report.comments.count} コメント", admin_report_path(report.id) %></td>
        <td><%= link_to "日報を見る", admin_report_path(report.id), class:'btn btn-success' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4"><%= paginate(@reports) %></div>
    <div class="col-lg-4"></div>
  </div>
</div>

app/views/admin/reports/show.html.erb
<h5>日報詳細</h5>
<div class="container">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">企業名</div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">登録者</div>
    <div class="col-lg-3"><%= @report.customer.name %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">内容</div>
    <div class="col-lg-3"><%= @report.report_text %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">結果</div>
    <div class="col-lg-3"><%= @result[@report.result] %></div>
    <div class="col-lg-3"></div>
  </div>
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">次回予定日</div>
    <div class="col-lg-3"><%= @report.next.to_s(:datetime_jp) %></div>
    <div class="col-lg-3"></div>
  </div>
</div>